### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by hjone72** [UnicornTranscoder/UnicornLoadBalancer#1]
Hi guys,

Wondering if you could post a sample nginx config. I am only using the load balancer and have made a few changes. Everything is working except for metadata images on Android clients. Still going through the process of diagnosing but thought your supported nginx config could help.
Great work on the project!
Thanks,

**Comment by drouarb** [comment]
https://gist.github.com/drouarb/a58d0e366ca6a018f65593479a414801

**Comment by hjone72** [comment]
Thanks for this. Unfortunately this is not the issue...
Just as a question for isolating down my issue, I assume you have tested and seen all metadata images loading correctly on Android clients?

**Comment by hjone72** [comment]
For reference, I've found the error. Android clients do not support http2 and if you enable http2 on any nginx virtual servers it enables on all of them.

Great work on the load balancer! Although I'm not using the Transcoder the LoadBalancer is exactly what I was looking for and is fantastic!
