### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by nightexcessive** [UnicornTranscoder/UnicornLoadBalancer#12]
I believe I've found a way to uniquely identify calls to the transcoder for Sync transcodings. When I attempted a Sync, the output file was:
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Cache/Transcode/Sync+/31352703/bf/437.mp3.temp`

Note the `Sync+` directory under the temporary transcode path. I haven't seen it use that directory for anything else. As such, I think we could send a request to a running transcoder to transcode with the given ffmpeg parameters. When it's done transcoding, we could have the transcoder upload the file back to the load balancer over HTTP(S) and the load balancer place it where Plex expects it. We would have to delay the last progress report from the transcoder until the upload was finished, otherwise Plex would try to access the file before it was there.

**Comment by Maxou44** [comment]
I think it works like the Media optimizer, we drafted the process for Media Optimizer here:
https://github.com/UnicornTranscoder/UnicornTranscoder/issues/4

**Comment by Maxou44** [comment]
![unknown](https://user-images.githubusercontent.com/8138585/55690395-6c15aa80-5991-11e9-8b9d-7863337c9756.png)

We worked on it, but it looks like Plex use 2-pass compression, a bit tricky too support, we'll continue our investigations, soon...

Note: DELETE request is disabled on "optimizer" branch

**Comment by Maxou44** [comment]
Solved in 2.2.0!
Have fun! Happy streaming!
