### ISSUE TITLE
Clients do not respond to 302s from LB

### ISSUE THREAD

**Issue by davidjameshowell** [UnicornTranscoder/UnicornLoadBalancer#13]
This isn't specifically an issue related to Unicorn as far as I can tell, but I wanted to confirm behavior from others that there are certain devices that do not respect the customer server URL; they will simply start, wait about 45 seconds, then fail with a non-specific error. So far:

Vizio TVs (Smart TV w/ apps)
PS3/PS4 Plex App
Chromecast
Xbox One?

It appears from my testing that these clients may or may not use the load balancer for communications, but do not respect the 302 to the transcoder.

Have your team seen the same behavior?

**Comment by Maxou44** [comment]
Remove Plex Relay binary, restart Plex Media Server and retry 🙂

**Comment by davidjameshowell** [comment]
Perfect! That seems to have worked! I am dealing with some secondary issues, but removing Relay allowed Chromecast to start functioning.

Can a note be added in the Readme to denote this?

**Comment by Maxou44** [comment]
I updated the README with "You also need to remove the Plex Relay binary.", I hope it's clear 😜
