### ISSUE TITLE
DOWNLOAD FAILED 1 [LB]

### ISSUE THREAD

**Issue by Silencedpulse** [UnicornTranscoder/UnicornLoadBalancer#16]
I have dockerized UnicornLoadBalancer, FFMPEG & Transcoder.  I have it working successfully when Plex and LoadBalancer are running in the same container but when I try to have them separate I get a "DOWNLOAD FAILED 1 [LB]" when debugging.  In both instances I have the Transcoder running in a separate docker container.  The LoadBalancer container is mapped to the SQLITE path of Plex (otherwise it crashed due to inaccessibility to the SQL database), I've also mapped the PLEX_PATH_SESSIONS and PLEX_PATH_USR paths to the LoadBalancer container.
All containers are running on the same system for this test.  I've updated the FFMPEG path as well so I'm not sure what I'm missing.

Thank you.

**Comment by Maxou44** [comment]
Can you give us your configuration values ?
