### ISSUE TITLE
Verbose/Debug Logging

### ISSUE THREAD

**Issue by dhowellbc** [UnicornTranscoder/UnicornLoadBalancer#2]
It's be helpful to have a flag to enable verbose/debug logging to investigate errors within the stack. Currently it's more difficult to diagnose errors that may arise between the three components.

**Comment by Maxou44** [comment]
Logs are available for the transcoder part, we will work on logs on the load balancer in the upcoming months, feel free to make a pull request if you work on it sooner.

**Comment by Maxou44** [comment]
The new version will log everything. We will release it soon I hope.

**Comment by Maxou44** [comment]
Logs are enabled in https://github.com/UnicornTranscoder/UnicornLoadBalancer/tree/wip-v2
