### ISSUE TITLE
Images not longer load in mobile apps

### ISSUE THREAD

**Issue by cruex-de** [UnicornTranscoder/UnicornLoadBalancer#23]
Hey,

I am currently experiencing a problem where my series or movie images cannot be downloaded into the Plex Mobile Apps...

I already tried to activate the "CUSTOM_IMAGE_PROXY", even without success.

Plex Version: 1.17.0.1841-d42cfa161
LoadBalancer Version: v2.4.0
Mobile App iOS Version: 6.4.1

![mobile-app](https://user-images.githubusercontent.com/6332358/69023514-4ccb0b00-09bf-11ea-8bd5-850514deeef9.jpeg)

**Comment by davidjameshowell** [comment]
Can you share some logs from your load balancer? Do you see any transcode errors or otherwise errors in the image proxy?
