### ISSUE TITLE
Plex client hanging when awaiting transcode

### ISSUE THREAD

**Issue by Orbsa** [UnicornTranscoder/UnicornLoadBalancer#27]
So I have the two servers
1. Unraid; Dockers for Plex, LetsEncrypt (Reverse Proxy), UnicornLoadBalancer
2. Ubuntu; UnicornTranscoder Direct installed and LetsEncrypt through Docker

After setting up everything how it should be I get the following.
- LoadBalancer/api/stats shows my remote transcoder connected
- Network Investigation shows start.mpd 302 redirecting to transcoder
- LoadBalancer/api/session/[sessionkey] shows everything proper
- Transcoder shows ffmpeg commands on session connect when logs are enabled

However, chunks are not reaching the end client;
A GET to https://mytranscod.er/video/:/transcode/.... returns 404 

Please see the attached [Transcoder.logs.txt](https://github.com/UnicornTranscoder/UnicornLoadBalancer/files/4238229/Transcoder.logs.txt)

**Comment by Maxou44** [comment]
Maybe @drouarb could check? I didn't find the solution 😅

**Comment by drouarb** [comment]
I don't see any FFMPEG callback, you should check if your FFMPEG is running and if the chunks are created in `cache/<sessionId>` folder. Maybe your transcoder server isn't powerful enough, or there is a problem with the callback. The UnicornTranscoder should be accessible for the FFMPEG process with http://127.0.0.1:<port>.

**Comment by Maxou44** [comment]
I'll close this issue, feel free to reopen it if needed
