### ISSUE TITLE
UnicornLoadBalancer won't start

### ISSUE THREAD

**Issue by koevoet1221** [UnicornTranscoder/UnicornLoadBalancer#45]
Hi, I was following this guide: https://blog.techup.dev/2020/08/04/unicorntranscoder-installation-guide/
but when I did systemctl status unicornloadbalancer.service it gave an error:
● unicornloadbalancer.service - UnicornLoadBalancer
   Loaded: loaded (/etc/systemd/system/unicornloadbalancer.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-02-21 21:59:38 CET; 13min ago
     Docs: https://github.com/UnicornTranscoder/UnicornLoadBalancer
  Process: 12913 ExecStart=/usr/bin/npm start (code=exited, status=1/FAILURE)
 Main PID: 12913 (code=exited, status=1/FAILURE)

Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at Module.require (internal/modules/cjs/loader.js:598:17)
Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at require (internal/modules/cjs/helpers.js:11:18)
Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at Module._compile (internal/modules/cjs/loader.js:654:30)
Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at Module.load (internal/modules/cjs/loader.js:566:32)
Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
Feb 21 21:59:38 Nick-PC-Debian npm[12913]:     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
Feb 21 21:59:38 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Main process exited, code=exited, status=1/FAILURE
Feb 21 21:59:38 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Failed with result 'exit-code'.

thought this was strange so i went to the unicornloadbalancer folder and did npm start manually which gave this error: 
/opt/UnicornLoadBalancer$ sudo npm start

> unicorn-load-balancer@2.0.0 start /opt/UnicornLoadBalancer
> cross-env DEBUG=* node index.js

  UnicornLoadBalancer Redis not found, fallback on LocalSessionStore +0ms
  UnicornLoadBalancer WARNING: On restart all sessions will be lost +4ms
/opt/UnicornLoadBalancer/node_modules/sqlite3/lib/sqlite3.js:1
Error: Cannot find module '/opt/UnicornLoadBalancer/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node'
Require stack:
- /opt/UnicornLoadBalancer/node_modules/sqlite3/lib/sqlite3.js
- /opt/UnicornLoadBalancer/src/database/sqlite.js
- /opt/UnicornLoadBalancer/src/database/index.js
- /opt/UnicornLoadBalancer/src/core/sessions.js
- /opt/UnicornLoadBalancer/src/routes/api.js
- /opt/UnicornLoadBalancer/src/routes/index.js
- /opt/UnicornLoadBalancer/src/app.js
- /opt/UnicornLoadBalancer/index.js
    at Object.<anonymous> (/opt/UnicornLoadBalancer/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Generator.next (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unicorn-load-balancer@2.0.0 start: `cross-env DEBUG=* node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unicorn-load-balancer@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-21T21_01_37_588Z-debug.log

and this is what is inside of the log:

 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle unicorn-load-balancer@2.0.0~prestart: unicorn-load-balancer@2.0.0
6 info lifecycle unicorn-load-balancer@2.0.0~start: unicorn-load-balancer@2.0.0
7 verbose lifecycle unicorn-load-balancer@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle unicorn-load-balancer@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/UnicornLoadBalancer/node_$
9 verbose lifecycle unicorn-load-balancer@2.0.0~start: CWD: /opt/UnicornLoadBalancer
10 silly lifecycle unicorn-load-balancer@2.0.0~start: Args: [ '-c', 'cross-env DEBUG=* node index.js' ]
11 silly lifecycle unicorn-load-balancer@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle unicorn-load-balancer@2.0.0~start: Failed to exec start script
13 verbose stack Error: unicorn-load-balancer@2.0.0 start: `cross-env DEBUG=* node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid unicorn-load-balancer@2.0.0
15 verbose cwd /opt/UnicornLoadBalancer
16 verbose Linux 4.19.0-14-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error unicorn-load-balancer@2.0.0 start: `cross-env DEBUG=* node index.js`
22 error Exit status 1
23 error Failed at the unicorn-load-balancer@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

my unicornloadbalancer.service looks like this: 

[Unit]
Description=UnicornLoadBalancer
Documentation=https://github.com/UnicornTranscoder/UnicornLoadBalancer
After=network.target

[Service]
Restart=on-abnormal
Type=simple

User=root
Group=root

Environment=SERVER_PORT=3001
Environment=SERVER_PUBLIC=UsedToBeMyIP
Environment=PLEX_HOST=127.0.0.1
Environment=PLEX_PORT=32400
Environment=PLEX_PATH_USR=/usr/lib/plexmediaserver
Environment="PLEX_PATH_SESSIONS=/home/koevoet/Docker/config/plex/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions"
Environment="DATABASE_SQLITE_PATH=/home/koevoet/Docker/config/plex/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugi$
Environment=DATABASE_MODE=sqlite
Environment=CUSTOM_SCORES_TIMEOUT=10
Environment=CUSTOM_DOWNLOAD_FORWARD=false

WorkingDirectory=/opt/UnicornLoadBalancer/
ExecStart=/usr/bin/npm start

KillMode=mixed
KillSignal=SIGQUIT
TimeoutStopSec=5s

LimitNOFILE=1048576
LimitNPROC=512

NoNewPrivileges=true

[Install]
WantedBy=multi-user.target

this is on debian 10
does anyone know how I can fix this and what i did wrong?
greetings

**Comment by drouarb** [comment]
Your npm install went wrong, probably because you ran it as root

**Comment by koevoet1221** [comment]
Sorry didnt have alot of time in the past weeks so i kinda gave it up but I got more time now so i really want to get this running. I reinstalled node, npm and unicorn transcoder and finally got to a stage where i could get it running if i did npm start inside the folder so i thought maybe a restart would fix things since i reinstalled alot. After the restart it worked, it started when i did systemctl start, i restarted it again because a problem with something else and when it restarted it didnt work anymore, without changing anything. Npm start still works but systemctl doesnt. 
Dont think it’ll be useful but this is the log when i use npm start: [https://pastebin.com/TukqXycW](url)
This is what my systemctl file looks like: [https://imgur.com/a/TV8DJKi](url)
This is what systemctl status gives: [https://imgur.com/a/tZV0cpD](url)

what am I doing wrong?

**Comment by koevoet1221** [comment]
Sorry didnt have alot of time in the past weeks so i kinda gave it up but I got more time now so i really want to get this running. I reinstalled node, npm and unicorn transcoder and finally got to a stage where i could get it running if i did npm start inside the folder so i thought maybe a restart would fix things since i reinstalled alot. After the restart it worked, it started when i did systemctl start, i restarted it again because a problem with something else and when it restarted it didnt work anymore, without changing anything. Npm start still works but systemctl doesnt. 
Dont think it’ll be usefull hut this is the lig when i use npm start: https://pastebin.com/TukqXycW
This is what my systemctl file looks like: [https://imgur.com/a/TV8DJKi](url)
This is what systemctl status gives:

**Comment by drouarb** [comment]
It would be nice to give us the full stack trace of the crash, you can get it with `journalctl -u unicornloadbalancer -e`
From what I see you have a node module loading problem.
It looks like your WorkingDirectory isn't where your UnicornLoadBalancer is installed.

**Comment by koevoet1221** [comment]
Hi, the command outputs this:
Apr 14 07:21:10 Nick-PC-Debian npm[750]: - /usr/share/npm/lib/utils/unsupported.js
Apr 14 07:21:10 Nick-PC-Debian npm[750]: - /usr/share/npm/bin/npm-cli.js
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     at Module.require (internal/modules/cjs/loader.js:952:19) {
Apr 14 07:21:10 Nick-PC-Debian npm[750]:   code: 'MODULE_NOT_FOUND',
Apr 14 07:21:10 Nick-PC-Debian npm[750]:   requireStack: [
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     '/usr/share/npm/lib/utils/unsupported.js',
Apr 14 07:21:10 Nick-PC-Debian npm[750]:     '/usr/share/npm/bin/npm-cli.js'
Apr 14 07:21:10 Nick-PC-Debian npm[750]:   ]
Apr 14 07:21:10 Nick-PC-Debian npm[750]: }
Apr 14 07:21:11 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 07:21:11 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Failed with result 'exit-code'.
~

**Comment by drouarb** [comment]
still not enough, we need the head of the stacktrace, that's where the error is located

**Comment by koevoet1221** [comment]
This?
koevoet@Nick-PC-Debian:/opt$ sudo journalctl -u unicornloadbalancer -e
Apr 14 18:09:17 Nick-PC-Debian npm[28583]: - /usr/share/npm/lib/utils/unsupported.js
Apr 14 18:09:17 Nick-PC-Debian npm[28583]: - /usr/share/npm/bin/npm-cli.js
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module.require (internal/modules/cjs/loader.js:952:19) {
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:   code: 'MODULE_NOT_FOUND',
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:   requireStack: [
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     '/usr/share/npm/lib/utils/unsupported.js',
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     '/usr/share/npm/bin/npm-cli.js'
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:   ]
Apr 14 18:09:17 Nick-PC-Debian npm[28583]: }
Apr 14 18:09:17 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 18:09:17 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Failed with result 'exit-code'.
lines 34-53/53 (END)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]: - /usr/share/npm/lib/utils/unsupported.js
Apr 14 18:09:17 Nick-PC-Debian npm[28583]: - /usr/share/npm/bin/npm-cli.js
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module.require (internal/modules/cjs/loader.js:952:19)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at require (internal/modules/cjs/helpers.js:88:18)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module.load (internal/modules/cjs/loader.js:928:32)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     at Module.require (internal/modules/cjs/loader.js:952:19) {
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:   code: 'MODULE_NOT_FOUND',
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:   requireStack: [
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     '/usr/share/npm/lib/utils/unsupported.js',
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:     '/usr/share/npm/bin/npm-cli.js'
Apr 14 18:09:17 Nick-PC-Debian npm[28583]:   ]
Apr 14 18:09:17 Nick-PC-Debian npm[28583]: }
Apr 14 18:09:17 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 18:09:17 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Failed with result 'exit-code'.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 34-53/53 (END)

**Comment by drouarb** [comment]
try removing tour node_modules folder and reinstall with npm i ?
Don't ru npm i as root, it create problems with post-install scripts

**Comment by koevoet1221** [comment]
Where can i find the node_modules folder? Sorry never used nodejs before

**Comment by drouarb** [comment]
in the unicornloadbalancer folder, it's the folder containing all dependecies for a running software

**Comment by koevoet1221** [comment]
Here is the npm install log https://pastebin.com/nBAyreUn
Sadly my ssh client cut the top off, some purple warnings about sqlite.
Node version: v14.16.1
Unicorn load balancer is in /opt/UnicornLoadBalancer like the tutorial i mentioned above.

**Comment by koevoet1221** [comment]
In my opinion the weirdest thing is that when i go to /opt/unicornloadbalancer and do npm start it runs fine and i can even access plex if i go to the ip but it is of course missing the environment variables this way

**Comment by drouarb** [comment]
It still looks like there is a part of the trace that is missing, it should say Cannot Require module <something>

**Comment by koevoet1221** [comment]
You mean the journalctl -u unicornloadbalancer -e command? Ill run it again in another terminal

**Comment by drouarb** [comment]
yes, but in this command you can scroll with arrows

**Comment by koevoet1221** [comment]
Left to right you mean? It moves the text to the left but nothing new appears.
This is everything it gives, this was ran in the standard terminal debian desktop comes with

**Comment by koevoet1221** [comment]
Is there a way to export this log to a file

**Comment by drouarb** [comment]
up and down you should scroll the log

**Comment by koevoet1221** [comment]
Used this command: sudo journalctl -u unicornloadbalancer -e > log.txt
Heres the text file https://linksharing.samsungcloud.com/u8fYKbfcUe2i

**Comment by drouarb** [comment]
https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver

**Comment by koevoet1221** [comment]
It does scroll, im stupid. Here is what it says https://pastebin.com/5Sc8HHvk

**Comment by koevoet1221** [comment]
I deleted those folders and I'm reinstalling node right now, I used make to build and install it, can that be the problem?

**Comment by drouarb** [comment]
Yes that can be a problem, you should use your OS prebuilt, it would be easier

**Comment by koevoet1221** [comment]
But thats version 9 or so, thats giving other issues and then npm start in the folder doesnt even work and recommends upgrading node.

**Comment by koevoet1221** [comment]
Dont know what i did but i uninstalled the make version and now its running :D but had this once before and after a restart it didnt anymore so im gonna do that now and see if it keeps working

**Comment by drouarb** [comment]
NodeJS team provides repositories with latest version, you should try to add them

**Comment by koevoet1221** [comment]
And it doesnt work after reboot ;(
This is the journalctl log:
-- Logs begin at Wed 2021-04-14 19:31:13 CEST, end at Wed 2021-04-14 19:34:20 CEST. --
Apr 14 19:31:30 Nick-PC-Debian systemd[1]: Started UnicornLoadBalancer.
Apr 14 19:32:00 Nick-PC-Debian npm[741]: npm WARN npm npm does not support Node.js v10.24.0
Apr 14 19:32:00 Nick-PC-Debian npm[741]: npm WARN npm You should probably upgrade to a newer version of node as we
Apr 14 19:32:00 Nick-PC-Debian npm[741]: npm WARN npm can't make any promises that npm will work with this version.
Apr 14 19:32:00 Nick-PC-Debian npm[741]: npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
Apr 14 19:32:00 Nick-PC-Debian npm[741]: npm WARN npm You can find the latest version at https://nodejs.org/
Apr 14 19:32:05 Nick-PC-Debian npm[741]: > unicorn-load-balancer@2.0.0 start /opt/UnicornLoadBalancer
Apr 14 19:32:05 Nick-PC-Debian npm[741]: > cross-env DEBUG=* node index.js
Apr 14 19:32:31 Nick-PC-Debian npm[741]: 2021-04-14T17:32:31.405Z UnicornLoadBalancer Redis not found, fallback on LocalSessionStore
Apr 14 19:32:31 Nick-PC-Debian npm[741]: 2021-04-14T17:32:31.408Z UnicornLoadBalancer WARNING: On restart all sessions will be lost
Apr 14 19:32:37 Nick-PC-Debian npm[741]: /opt/UnicornLoadBalancer/node_modules/sqlite3/lib/sqlite3.js:1
Apr 14 19:32:37 Nick-PC-Debian npm[741]: Error: Cannot find module '/opt/UnicornLoadBalancer/node_modules/sqlite3/lib/binding/node-v64-linux-Apr 14 19:32:37 Nick-PC-Debian npm[741]: Require stack:
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/node_modules/sqlite3/lib/sqlite3.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/src/database/sqlite.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/src/database/index.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/src/core/sessions.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/src/routes/api.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/src/routes/index.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/src/app.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]: - /opt/UnicornLoadBalancer/index.js
Apr 14 19:32:37 Nick-PC-Debian npm[741]:     at Object.<anonymous> (/opt/UnicornLoadBalancer/node_modules/sqlite3/lib/sqlite3.js:4:15)
Apr 14 19:32:37 Nick-PC-Debian npm[741]:     at Generator.next (<anonymous>)
Apr 14 19:32:37 Nick-PC-Debian npm[741]: npm ERR! code ELIFECYCLE
Apr 14 19:32:37 Nick-PC-Debian npm[741]: npm ERR! errno 1
Apr 14 19:32:37 Nick-PC-Debian npm[741]: npm ERR! unicorn-load-balancer@2.0.0 start: `cross-env DEBUG=* node index.js`
Apr 14 19:32:37 Nick-PC-Debian npm[741]: npm ERR! Exit status 1
Apr 14 19:32:37 Nick-PC-Debian npm[741]: npm ERR!
Apr 14 19:32:37 Nick-PC-Debian npm[741]: npm ERR! Failed at the unicorn-load-balancer@2.0.0 start script.
Apr 14 19:32:37 Nick-PC-Debian npm[741]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Apr 14 19:32:38 Nick-PC-Debian npm[741]: npm ERR! A complete log of this run can be found in:
Apr 14 19:32:38 Nick-PC-Debian npm[741]: npm ERR!     /root/.npm/_logs/2021-04-14T17_32_37_856Z-debug.log
Apr 14 19:32:38 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 19:32:38 Nick-PC-Debian systemd[1]: unicornloadbalancer.service: Failed with result 'exit-code'.

Looks like im missing sqlite3? How to get it?

**Comment by drouarb** [comment]
it should be installed by npm install

**Comment by drouarb** [comment]
I think you should remove your node_modules and reinstall, i think that nodegyp module need to ne rebuilt when changing node version

**Comment by koevoet1221** [comment]
I'm installing node from their repository now should I do npm I again?

**Comment by drouarb** [comment]
remove your node_modules folder and npm install

**Comment by koevoet1221** [comment]
Okay nvm I'll do that

**Comment by koevoet1221** [comment]
It's working now, even after a reboot. Thank you so much for your help. Hope I can now install the rest without issues
